### ISSUE TITLE
is this still working?

### ISSUE THREAD

**Issue by BaeBae33** [nubomedia-vtt/kurento-room-client-android#1]
I was trying to connect to my http's room.There is not any error in LogCat.But connectionstate was NOT_YET_CONNECT.Im doubt that if your codes still works.

**Comment by BaeBae33** [comment]
Finally,I find the way to dealwith this problem.Client.Connect is a time consuming operation.So we should not do roomApi.isWebSocketConnected() after connect immediately.

**Comment by jpsjanne** [comment]
RoomListener interface also implements event onRoomConnected() which is triggered when the websocket connection is opened successfully.
