### ISSUE TITLE
How to implement one to one video call in android?

### ISSUE THREAD

**Issue by ananth10** [nubomedia-vtt/kurento-room-client-android#5]
I need to implement OneToOne video call function in android . can anyone tell me how to do and is there any sample code?

**Comment by jpsjanne** [comment]
The best place to start is nubo-test, a demonstration program for Kurento Android libraries
https://github.com/nubomedia-vtt/nubo-test

Be sure to check the documentation of both webrtcpeer-android and kurento-room-client-android:
http://doc-webrtcpeer-android.readthedocs.io/en/latest/
http://doc-kurento-room-client-android.readthedocs.io/en/latest/

If you need further help, the best place to ask for help is our Google group:
https://groups.google.com/forum/#!forum/nubomedia-dev

**Comment by ananth10** [comment]
@jpsjanne  Thank you so much..

**Comment by SohailYaseen** [comment]
What is the difference between webrtcpeer-android and kurento-room-client-android?

**Comment by SohailYaseen** [comment]
@jpsjanne what is the difference between webrtcpeer-android and kurento-room-client-android?

**Comment by jpsjanne** [comment]
@SohailYaseen webrtcpeer-android handles multimedia communication from one peer to another, while kurento-room-client-android provides a way for users to form "rooms" where said communications can be established.

**Comment by SohailYaseen** [comment]
server needed in both ways?

**Comment by SohailYaseen** [comment]
i want to implement one to one  Video calling, audio calling and text messaging in android app. Can you please guide me how to achieve this or please share any example.

**Comment by jpsjanne** [comment]
@SohailYaseen I'm not working for this project anymore so I don't have the latest materials, but I can at least say that you are going to need both room-client and webrtcpeer libraries, even if it's just p2p. I'd say that the best place to start is to take nubo-test https://github.com/nubomedia-vtt/nubo-test and see if it how that works. It was originally designed as p2p calling app.

Yes, you need to install Kurento Media Server. As far as I know, it is required for both room signalling and multimedia traffic. I have no experience with KMS, so you might want to ask the Kurento people for instructions.

**Comment by SohailYaseen** [comment]
Any resource to contact  Kurento people!?

**Comment by jpsjanne** [comment]
No, but you can google around and find pretty good material as well. The project is well-maintained.
https://github.com/Kurento/kurento-media-server

**Comment by SohailYaseen** [comment]
Thank you

**Comment by vviek** [comment]
@sohailYaseen .I have implemented the video chat for multiple user using
kurento media servee. If you want any help you can mail me at
vivek.patel371@gmail.com
Or contact at 9993821365

**Comment by SohailYaseen** [comment]
@jpsjanne janne do you know anything about this exception?

PeerVideoActivity: OnRoomError:RoomError: -1 - org.kurento.client.internal.server.KurentoServerException: Endpoint already negotiated (Code:40208, Type:null, Data: {"type":"SDP_END_POINT_ALREADY_NEGOTIATED"})

**Comment by dattatraynande** [comment]
Hello,
I try with https://github.com/nubomedia-vtt/nubo-test
but not able to join room, getting disconnect dialog, "You have been disconnected"

Log:
 E/KurentoRoomAPI: onError: null
                                                               java.nio.channels.UnresolvedAddressException
                                                                   at java.nio.SocketChannelImpl.validateAddress(SocketChannelImpl.java:444)
                                                                   at java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:163)
                                                                   at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:210)
                                                                   at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
                                                                   at java.lang.Thread.run(Thread.java:841)

**Comment by dkvbabu** [comment]
HI  Janne Seppänen,

I am using your android project for p2p call on android phone. I was able to import into Android studio and build successfully. Please let me know how to run this app on mobile device by creating apk file.
I tried Build -> Build APK but not doing anything and not finding apk file.
Also I am new to Android development.

Regards
dk venkatesh babu

**Comment by dkvbabu** [comment]
Hi vivek.patel,SohailYaseen ,

You can also reply 
Regards
